name: remotes install on windows

on:
  pull_request


jobs:
  install-check:
    runs-on: windows-latest

    steps:
      - uses: r-lib/actions/setup-r@v1

      - name: Install {remotes}
        run: |
          install.packages("remotes")
        shell: Rscript {0}

      - name: Test install
        run: |
          remotes::install_github(repo="Olink-Proteomics/Nexus-R", ref="${{ github.event.pull_request.head.sha }}", subdir="nexusr", auth_token="${{ secrets.GITHUB_TOKEN }}")
        shell: Rscript {0}

